version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=user_password
      - DB_NAME=login_db
      - DB_PORT=3306
    depends_on:
      - db
    volumes:
      - ./app:/app  # Only mount the `app` folder to `/app` in the container
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: login_db            # Name of the database
      MYSQL_USER: user                    # Database username
      MYSQL_PASSWORD: user_password       # Database password
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql  # Initialize database on startup

volumes:
  db_data:
