version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - env_file.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: login_db            # Name of the database
      MYSQL_USER: user                    # Database username
      MYSQL_PASSWORD: user_password       # Database password
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MySQL
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql  # Initialize database on startup

volumes:
  db_data:
